export interface Technology {
  href: string;
  imageSrc: string;
  name: string;
}

export const vendorImages : Technology[] = [{
  href: 'https://git-scm.com/',
  imageSrc: 'assets/technologies/git.png',
  name: 'Git'
}, {
  href: 'https://www.oracle.com/java/index.html',
  imageSrc: 'assets/technologies/java.png',
  name: 'Java'
}, {
  href: 'https://www.python.org/',
  imageSrc: 'assets/technologies/python.png',
  name: 'Python'
}, {
  href: 'https://isocpp.org/',
  imageSrc: 'assets/technologies/cpp_logo.png',
  name: 'C++'
}, {
  href: 'https://www.wikiwand.com/en/C_(programming_language)',
  imageSrc: 'assets/technologies/C.png',
  name: 'C'
}, {
  href: 'https://isocpp.org/',
  imageSrc: 'assets/technologies/csharp.png',
  name: 'C#'
}, {
  href: 'https://www.typescriptlang.org/',
  imageSrc: 'assets/technologies/typescript.png',
  name: 'Typescript'
}, {
  href: 'https://www.mathworks.com/products/matlab.html',
  imageSrc: 'assets/technologies/MATLAB.jpeg',
  name: 'MATLAB'
}, {
  href: 'https://angular.io/',
  imageSrc: 'assets/technologies/angular.svg',
  name: 'Angular'
}, {
  href: 'https://facebook.github.io/react/',
  imageSrc: 'assets/technologies/react.png',
  name: 'React'
}, {
  href: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
  imageSrc: 'assets/technologies/javascript.png',
  name: 'Javascript6'
}, {
  href: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
  imageSrc: 'assets/technologies/html.png',
  name: 'HTML5'
}, {
  href: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
  imageSrc: 'assets/technologies/css.png',
  name: 'CSS3'
}, {
  href: 'https://firebase.google.com/',
  imageSrc: 'assets/technologies/firebase.png',
  name: 'Firebase'
}, {
  href: 'https://www.ruby-lang.org/en/',
  imageSrc: 'assets/technologies/ruby.png',
  name: 'Ruby'
}, {
  href: 'https://developer.apple.com/swift/',
  imageSrc: 'assets/technologies/swift.png',
  name: 'Swift'
}, {
  href: 'https://www.android.com/',
  imageSrc: 'assets/technologies/android.png',
  name: 'Android'
}, {
  href: 'https://developer.apple.com/ios/',
  imageSrc: 'assets/technologies/ios.jpg',
  name: 'IOS'
}, {
  href: 'http://github.com/',
  imageSrc: 'assets/technologies/github.png',
  name: 'Github'
}, {
  href: 'https://www.docker.com/',
  imageSrc: 'assets/technologies/docker.svg',
  name: 'Docker'
}, {
  href: 'http://hadoop.apache.org/',
  imageSrc: 'assets/technologies/hadoop.png',
  name: 'Hadoop'
}, {
  href: 'https://pig.apache.org/',
  imageSrc: 'assets/technologies/pig.png',
  name: 'Pig'
}, {
  href: 'https://hive.apache.org/',
  imageSrc: 'assets/technologies/hive.png',
  name: 'Hive'
}, {
  href: 'http://lucene.apache.org/solr/',
  imageSrc: 'assets/technologies/solr.png',
  name: 'Solr'
}, {
  href: 'https://spark.apache.org/',
  imageSrc: 'assets/technologies/spark.png',
  name: 'Spark'
}, {
  href: 'http://oozie.apache.org/',
  imageSrc: 'assets/technologies/oozie.png',
  name: 'Oozie'
}, {
  href: 'http://sqoop.apache.org/',
  imageSrc: 'assets/technologies/sqoop.png',
  name: 'Sqoop'
}, {
  href: 'https://zookeeper.apache.org/',
  imageSrc: 'assets/technologies/zookeeper.png',
  name: 'zookeeper'
}, {
  href: 'https://kafka.apache.org/',
  imageSrc: 'assets/technologies/kafka.png',
  name: 'kafka'
}, {
  href: 'http://maven.apache.org/',
  imageSrc: 'assets/technologies/maven.png',
  name: 'Maven'
}, {
  href: 'https://gradle.org/',
  imageSrc: 'assets/technologies/gradle.png',
  name: 'Gradle'
}, {
  href: 'https://projects.spring.io/spring-boot/',
  imageSrc: 'assets/technologies/spring-boot.png',
  name: 'Spring Boot'
}, {
  href: 'https://nodejs.org/',
  imageSrc: 'assets/technologies/nodejs.svg',
  name: 'Node.js'
}, {
  href: 'https://www.npmjs.com/',
  imageSrc: 'assets/technologies/npm.svg',
  name: 'npm'
}, {
  href: 'https://yarnpkg.com/en/',
  imageSrc: 'assets/technologies/yarn.png',
  name: 'Yarn'
}, {
  href: 'https://webpack.github.io',
  imageSrc: 'assets/technologies/webpack.png',
  name: 'Webpack'
}, {
  href: 'http://getbootstrap.com/',
  imageSrc: 'assets/technologies/boostrap.png',
  name: 'Boostrap'
}, {
  href: 'http://fontawesome.io/',
  imageSrc: 'assets/technologies/font-awesome.png',
  name: 'Font Awesome'
}, {
  href: 'https://karma-runner.github.io',
  imageSrc: 'assets/technologies/karma.png',
  name: 'Karma'
}, {
  href: 'http://gulpjs.com/',
  imageSrc: 'assets/technologies/gulp.png',
  name: 'Gulp'
}, {
  href: 'http://mochajs.org/',
  imageSrc: 'assets/technologies/mocha.svg',
  name: 'Mocha'
}, {
  href: 'http://sass-lang.com/',
  imageSrc: 'assets/technologies/sass.svg',
  name: 'Sass'
}, {
  href: 'https://www.mongodb.org/',
  imageSrc: 'assets/technologies/mongodb.svg',
  name: 'Mongodb'
}, {
  href: 'https://redis.io/',
  imageSrc: 'assets/technologies/redis.svg',
  name: 'Redis'
}, {
  href: 'http://expressjs.com/',
  imageSrc: 'assets/technologies/express.png',
  name: 'express'
}, {
  href: 'https://material.io/',
  imageSrc: 'assets/technologies/material-design.png',
  name: 'Material Design'
}, {
  href: 'http://socket.io/',
  imageSrc: 'assets/technologies/socketio.svg',
  name: 'socket.io'
}, {
  href: 'https://babeljs.io/',
  imageSrc: 'assets/technologies/babel.png',
  name: 'Babel'
}, {
  href: 'http://flask.pocoo.org/',
  imageSrc: 'assets/technologies/flask.png',
  name: 'Flask'
}, {
  href: 'https://developer.chrome.com/extensions',
  imageSrc: 'assets/technologies/chrome-extension.png',
  name: 'Chrome Extension'
}, {
  href: 'http://www.graphviz.org/',
  imageSrc: 'assets/technologies/GraphvizLogo.png',
  name: 'GraphViz'
}, {
  href: 'http://www.ni.com/en-us/shop/labview.html',
  imageSrc: 'assets/technologies/LabVIEW.png',
  name: 'LabVIEW'
}, {
  href: 'http://www.scheme.com/tspl4/',
  imageSrc: 'assets/technologies/Lambda_lc.svg.png',
  name: 'Scheme'
}, {
  href: 'https://tla.msr-inria.inria.fr/tlaps/content/Home.html',
  imageSrc: 'assets/technologies/TLA+.png',
  name: 'TLA+'
}];
