export interface Technology {
  href: string;
  imageSrc: string;
  name: string;
}

export const vendorImages : Technology[] = [{
  href: 'https://git-scm.com/',
  imageSrc: 'assets/git.png',
  name: 'Git'
}, {
  href: 'https://www.oracle.com/java/index.html',
  imageSrc: 'assets/java.png',
  name: 'Java'
}, {
  href: 'https://www.python.org/',
  imageSrc: 'assets/python.png',
  name: 'Python'
}, {
  href: 'https://isocpp.org/',
  imageSrc: 'assets/cpp_logo.png',
  name: 'C++'
}, {
  href: 'https://www.mathworks.com/products/matlab.html',
  imageSrc: 'assets/MATLAB.jpeg',
  name: 'MATLAB'
}, {
  href: 'https://angular.io/',
  imageSrc: 'assets/images/angular.svg',
  name: 'Angular'
}, {
  href: 'https://facebook.github.io/react/',
  imageSrc: 'assets/images/react.svg',
  name: 'React'
}, {
  href: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
  imageSrc: 'assets/javascript.png',
  name: 'Javascript6'
}, {
  href: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
  imageSrc: 'assets/html.png',
  name: 'HTML5'
}, {
  href: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
  imageSrc: 'assets/css.png',
  name: 'CSS3'
}, {
  href: 'https://www.typescriptlang.org/',
  imageSrc: 'assets/typescript.png',
  name: 'Typescript'
}, {
  href: 'https://firebase.google.com/',
  imageSrc: 'assets/firebase.png',
  name: 'Firebase'
}, {
  href: 'https://www.android.com/',
  imageSrc: 'assets/android.png',
  name: 'Android'
}, {
  href: 'https://developer.apple.com/ios/',
  imageSrc: 'assets/ios.jpg',
  name: 'IOS'
}, {
  href: 'http://github.com/',
  imageSrc: 'assets/github.png',
  name: 'Github'
}, {
  href: 'https://www.docker.com/',
  imageSrc: 'assets/images/docker.svg',
  name: 'Docker'
}, {
  href: 'http://hadoop.apache.org/',
  imageSrc: 'assets/hadoop.png',
  name: 'Hadoop'
}, {
  href: 'https://hive.apache.org/',
  imageSrc: 'assets/hive.png',
  name: 'Hive'
}, {
  href: 'http://lucene.apache.org/solr/',
  imageSrc: 'assets/solr.png',
  name: 'Solr'
}, {
  href: 'https://spark.apache.org/',
  imageSrc: 'assets/spark.png',
  name: 'Spark'
}, {
  href: 'http://oozie.apache.org/',
  imageSrc: 'assets/oozie.png',
  name: 'Oozie'
}, {
  href: 'http://sqoop.apache.org/',
  imageSrc: 'assets/sqoop.png',
  name: 'Sqoop'
}, {
  href: 'https://zookeeper.apache.org/',
  imageSrc: 'assets/zookeeper.png',
  name: 'zookeeper'
}, {
  href: 'https://kafka.apache.org/',
  imageSrc: 'assets/kafka.png',
  name: 'kafka'
}, {
  href: 'https://projects.spring.io/spring-boot/',
  imageSrc: 'assets/spring-boot.png',
  name: 'Spring Boot'
}, {
  href: 'https://nodejs.org/',
  imageSrc: 'assets/images/nodejs.svg',
  name: 'Node.js'
}, {
  href: 'https://www.npmjs.com/',
  imageSrc: 'assets/images/npm.svg',
  name: 'npm'
}, {
  href: 'https://yarnpkg.com/en/',
  imageSrc: 'assets/yarn.png',
  name: 'Yarn'
}, {
  href: 'https://webpack.github.io',
  imageSrc: 'assets/images/webpack.png',
  name: 'Webpack'
}, {
  href: 'http://getbootstrap.com/',
  imageSrc: 'assets/boostrap.png',
  name: 'Boostrap'
}, {
  href: 'http://fontawesome.io/',
  imageSrc: 'assets/font-awesome.png',
  name: 'Font Awesome'
}, {
  href: 'https://karma-runner.github.io',
  imageSrc: 'assets/images/karma.png',
  name: 'Karma'
}, {
  href: 'https://lodash.com/',
  imageSrc: 'assets/images/lodash.png',
  name: 'Lodash'
}, {
  href: 'http://gulpjs.com/',
  imageSrc: 'assets/images/gulp.png',
  name: 'Gulp'
}, {
  href: 'http://mochajs.org/',
  imageSrc: 'assets/mocha.svg',
  name: 'Mocha'
}, {
  href: 'http://sass-lang.com/',
  imageSrc: 'assets/images/sass.svg',
  name: 'Sass'
}, {
  href: 'https://www.mongodb.org/',
  imageSrc: 'assets/images/mongodb.svg',
  name: 'Mongodb'
}, {
  href: 'http://expressjs.com/',
  imageSrc: 'assets/images/express.png',
  name: 'express'
}, {
  href: 'https://material.io/',
  imageSrc: 'assets/material-design.png',
  name: 'Material Design'
}, {
  href: 'http://socket.io/',
  imageSrc: 'assets/images/socketio.svg',
  name: 'socketio'
}, {
  href: 'http://flask.pocoo.org/',
  imageSrc: 'assets/flask.png',
  name: 'Flask'
}, {
  href: 'https://developer.chrome.com/extensions',
  imageSrc: 'assets/chrome-extension.png',
  name: 'Chrome extension'
}, {
  href: 'http://www.ni.com/en-us/shop/labview.html',
  imageSrc: 'assets/LabVIEW.png',
  name: 'LabVIEW'
}, {
  href: 'http://www.scheme.com/tspl4/',
  imageSrc: 'assets/Lambda_lc.svg.png',
  name: 'Scheme'
}, {
  href: 'https://tla.msr-inria.inria.fr/tlaps/content/Home.html',
  imageSrc: 'assets/TLA+.png',
  name: 'TLA+'
}];
